# Generated by Django 5.2 on 2025-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0010_alter_facturation_total_acte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturation',
            name='lieu_acte',
        ),
        migrations.AlterField(
            model_name='facturation',
            name='regime',
            field=models.CharField(choices=[('Sécurité Sociale', 'Sécurité Sociale'), ('RNS', 'RNS'), ('Salarié', 'Salarié'), ('RST', 'RST')], max_length=20, verbose_name='Régime'),
        ),
    ]
