# Generated by Django 5.2 on 2025-05-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0011_remove_facturation_lieu_acte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_acte_normal_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code Acte Normal 2'),
        ),
        migrations.AddField(
            model_name='code',
            name='total_acte_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name="Montant total de l'acte 1"),
        ),
        migrations.AddField(
            model_name='code',
            name='total_acte_2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name="Montant total de l'acte 2"),
        ),
    ]
