# Generated by Django 5.2 on 2025-05-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0012_code_code_acte_normal_2_code_total_acte_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='lieu_acte',
            field=models.CharField(choices=[('cabinet', 'Cabinet'), ('clinique', 'Clinique')], default='Cabinet', max_length=50, verbose_name="Lieu de l'acte"),
        ),
    ]
